"""v16 patch — the recovered-data version of the manuscript.

Base: the ORIGINAL deposited v13 (manuscript_revised.tex from the fuller_workspace
release, SHA-256-verified against the GitHub release digest), NOT a reconstruction.

Applies:
  * the complete audit-3 v14 plan (E1-E9, N3, D6, N2; audit3_joint_assessment.md Sec. 4),
    with the wording cross-checked against the reconstructed v14/v15 in the repository;
  * the v15 spinor factorisation in the proof of the closed-form-spectrum Proposition;
  * the p_c re-centring 0.1595(10) -> 0.1597(8) authorised in the deposited session;
  * the v16 recovery verification: every caveat of the form "quoted from the deposit"
    is replaced by "recomputed from the recovered raw dataset", with the re-verification
    results (seed contract 44/44 bit-exact; 1/N-floor pipeline no-op on every window;
    purification rerun exact to the bit).

New version file only (versions/manuscript_revised_v16_recovered.tex); v13, the
reconstructed v14 and v15 are kept unmodified.  Every anchor is asserted before any
write; the result is lint-checked (no stray control characters, balanced braces).
"""
import re, sys

SRC = "manuscript_revised.tex"
DST = "versions/manuscript_revised_v16_recovered.tex"

src = open(SRC).read()
n0 = src.count("\n")

def rep(old, new, tag, count=1):
    global src
    assert src.count(old) == count, f"anchor {tag}: count={src.count(old)} (expected {count})"
    src = src.replace(old, new, count)
    print(f"  [ok] {tag}")

# ---------------------------------------------------------------- header
rep("% Revised manuscript implementing audit_adjudication.md (Sept 2026).",
    "% v16 (recovered-data version), built from the ORIGINAL deposited v13 of the\n"
    "% fuller_workspace release: the full audit-3 v14 plan (E1-E9, N3, D6, N2), the v15\n"
    "% spinor factorisation, the authorised p_c re-centring 0.1595(10)->0.1597(8), and\n"
    "% the end-to-end re-verification on the recovered raw dataset (seed contract 44/44\n"
    "% bit-exact; released 1/N-floor pipeline reproduces every windowed number; the\n"
    "% purification analysis reproduces every deposited number to the bit).\n"
    "% Revised manuscript implementing audit_adjudication.md (Sept 2026).",
    "header")

# ---------------------------------------------------------------- abstract: one sentence on the new exact content
rep("This exact solution benchmarks the transfer-matrix chain; the annealed point is distinct from the quenched, Born-weighted transition.",
    "This exact solution benchmarks the transfer-matrix chain; its complete nonzero spectrum is obtained in closed free-fermion form, fixing the finite-size amplitudes at the annealed point exactly; and the annealed point is distinct from the quenched, Born-weighted transition, whose critical point an independent purification locator with disjoint seeds confirms.",
    "abstract-D6-N2")

# ---------------------------------------------------------------- E5: sampling convention (l. 1111)
rep("and every gate an independent uniformly random two-qubit Clifford.",
    "and every gate an independent uniformly random two-qubit Clifford (sampled as the $720$ symplectic actions, under which every recorded quantity is invariant).",
    "E5-sampling")

# ---------------------------------------------------------------- E9: seed contract (l. 1111)
rep("each an independent disorder sample.",
    "each an independent disorder sample.  Trajectory $k$ of file $(L,p)$ is generated by the legacy MT19937 stream seeded with $\\mathit{seed0}(L,p)+k$, the value $\\mathit{seed0}$ being stored in the file; regeneration is bit-exact (re-verified on the recovered dataset for $44$ trajectories spanning $L=16$--$512$, including the $I_3\\equiv0$ file at $L=384$, $p=0.18$).",
    "E9-seeds")

# ---------------------------------------------------------------- data availability (l. 1109)
rep("Everything below is reproducible from the deposited simulator, raw trajectories and analysis scripts (Data and code availability); the full analysis, including all estimator and window variants, is in the deposited report.",
    "Everything below is reproducible from the deposited simulator, raw trajectories and analysis scripts (Data and code availability): the raw $I_3$ dataset ($192$ trajectory files, $475\\,600$ trajectories, $L=16$--$512$), the purification dataset ($270$ files, $135\\,000$ trajectories), every analysis script and every machine-readable result are deposited in the workspace release, and the full analysis, including all estimator and window variants, is in the deposited report.  The present revision re-verified the recovered dataset end to end: the seed contract above regenerates the test trajectories bit-exactly, the released $1/N$-floor pipeline reproduces every windowed number of Table~\\ref{tab:numerics} without change, and the purification analysis reproduces every deposited number to the bit.",
    "data-availability")

# ---------------------------------------------------------------- E3: omega_eff (l. 1121)
rep("gives $0.1602(6)$ ($\\omega\\approx1.7$)",
    "gives $0.1602(6)$ ($\\omega_{\\rm eff}=1.6(4)$--$2.5(8)$ depending on $L_{\\min}$)",
    "E3-omega")

# ---------------------------------------------------------------- E3: chi2 p-values (l. 1121)
rep("with $\\chi^2/{\\rm dof}\\approx1$ for $L\\ge64$.",
    "with $\\chi^2/{\\rm dof}=0.7$--$1.2$ for $L\\ge64$ and $|x|_{\\max}\\le1$ ($\\chi^2$ $p$-values $0.19$--$0.84$; $p\\ge0.40$ for $|x|_{\\max}=0.6$; the widest windows $|x|_{\\max}=1.5$ reach $\\chi^2/{\\rm dof}=1.5$--$2.0$, $p=8\\times10^{-6}$--$0.02$, through area-law-edge points).",
    "E3-pvalues")

# ---------------------------------------------------------------- re-centring (l. 1121)
rep("Adopted: $p_c=0.1595\\pm0.0010$, the interval covering all estimators; the statistical errors alone are $\\pm0.0003$.",
    "Adopted: $p_c=0.1597\\pm0.0008$, the interval covering all estimators (the corrected, tail-safe fixed-set fits centre at $0.1597$--$0.1598$; the statistical errors alone are $\\pm0.0003$).",
    "recenter-1121")

# ---------------------------------------------------------------- E2: exponent paragraph (l. 1123)
rep("with $\\nu$ frozen, the collapse $\\chi^2/{\\rm dof}$ ($t=2L$, $L=48$--$512$) is $5.3$, $2.7$, $1.6$, $2.1$, $5.5$ for $\\nu=1$, $1.15$, $1.24$, $4/3$, $1.45$.  Adopted: $\\nu=1.24\\pm0.07$; $\\nu=1$ is excluded, the percolation value $4/3$ is disfavoured at $1.3\\sigma$.",
    "with $\\nu$ frozen on \\emph{fixed} point sets ($L\\ge64$; spline scaling function with the area-law tail retained, over the eight tail-safe variants of the deposited report), the $\\Delta\\chi^2$ profiles are $52$--$334$ for $\\nu=1$, $0.2$--$11$ for $\\nu=1.20$, $0.1$--$2.6$ for $\\nu=1.24$, $0$--$9.9$ for $\\nu=1.28$, $3.0$--$36.5$ for $4/3$, and $12.5$--$89$ for $\\nu=1.40$ (sextic scaling function with the tail removed: $\\Delta\\chi^2(\\nu=1)\\ge72$).  A power-law correction to scaling $AL^{-\\omega}$ is preferred only when $L=48$ is retained ($\\Delta\\mathrm{AIC}=-7$ to $-14$), is neutral at $L\\ge64$ and disfavoured at $L\\ge96$, with $\\omega$ undetermined ($0.3$--$4$, bootstrap s.e.\\ $\\approx1$); it raises $\\nu$ by $0.02$--$0.04$.  We disclose the estimator weighting, whose defect biased earlier fixed-set fits: standard errors are floored at $1/N_{\\rm traj}$ per point in the released code (the legacy $10^{-4}$/$10^{-6}$ floors of the v13 analysis code, which let a single saturated point---$I_3\\equiv0$ in all $800$ trajectories at $L=384$, $p=0.18$---carry $98\\%$ of one fixed-set fit's weight, are replaced by $1/N$), and the area-law points, which a polynomial scaling function cannot be flat on, are either removed or given a spline scaling function; the released pipeline, re-run on the recovered raw dataset, reproduces every windowed number of Table~\\ref{tab:numerics} without change, confirming that no quoted window contains a floored point.  All $I_3$/entropy locators of this appendix share the same $475\\,600$ trajectories; the only independent observable is the purification protocol below (disjoint seeds, mixed initial state).  Adopted: $\\nu=1.24\\pm0.07$, covering the full tail-safe envelope $1.21$--$1.29$; $\\nu=1$ is excluded ($\\Delta\\chi^2\\ge52$ in every variant), and the percolation value $4/3$ is disfavoured ($\\Delta\\chi^2\\ge3$ in every variant, $\\ge20$ without a correction term) but not excluded by the weakest variant.",
    "E2-exponent")

# ---------------------------------------------------------------- E4 + alpha re-evaluation (l. 1125)
rep("gives $\\alpha=1.50$--$1.56$ (bootstrap $\\pm0.02$--$0.04$)",
    "gives $\\alpha=1.50$--$1.56$ (bootstrap $\\pm0.02$--$0.04$); a power-law correction $s_1L^{-y}$ ($y=\\tfrac12,1,2$) is at most weakly preferred ($\\Delta\\mathrm{AIC}\\ge-3$) and moves $\\alpha$ by at most $0.14$; and the straight-line rows re-evaluated at the adopted $p_c=0.1597$ (spline window $p\\in[0.145,0.175]$) give $\\alpha=1.53$--$1.59$, inside the adopted interval",
    "E4-alpha")

# ---------------------------------------------------------------- E1: tilt mechanism (l. 1127)
rep("at every size and $p$ (Jensen), the ratio growing",
    "at every size and $p$; the excess is a change-of-measure effect rather than a convexity one: the record-collision weight of the annealed channel, proportional to $p_R^2$, favours records with fewer measurements and lowers the effective monitoring rate to $p_{\\rm eff}=p+\\frac{p(1-p)}{2L}\\partial_p\\ln\\lambda_1$ ($0.105$ at $L=8$, $0.101$ at $L=12$, $0.092$ in the $L\\to\\infty$ limit at $p=0.16$; $0.149$ at $p_c^{(2)}$).  At $L=8$, $t=4$, $p=0.16$ ($40\\,000$ Born trajectories, effective sample size $5935$): $\\E_{\\rm Born}S=2.019(4)$, $\\E_{\\rm Born}S(p_{\\rm eff})=2.339(4)$, $\\E_{\\rm tilt}S=2.429$, exact $\\tilde S_2=2.155$ bits---the density shift alone accounts for ${\\approx}80\\%$ of the tilt gain $\\E_{\\rm tilt}S-\\E_{\\rm Born}S(p)=0.41$ bits, of which Jensen removes $0.27$ bits, leaving the observed excess $\\tilde S_2-\\E_{\\rm Born}S=0.14$ bits; at $L=12$ ($2.394(5)$, $2.941(4)$, $\\tilde S_2=3.128$) the ordering is the same (the sampled tilt average there, effective sample size $454$, is not reliable and is not used).  The ratio growing",
    "E1-tilt")

# ---------------------------------------------------------------- E6 + N2 (l. 1129)
rep("and $p_c=0.15995(10)$~\\cite{Sierant2022}.  The present values agree with all of them within the stated uncertainties.",
    "and $p_c=0.15995(10)$~\\cite{Sierant2022}.  Gullans and Huse~\\cite{Gullans2020} report $p_c=0.1593(5)$, $\\nu=1.28(2)$; the coefficient $\\tilde c\\approx1.5$--$1.6$ quoted in that literature equals our $\\alpha$ in units of $\\ln2$.  The present values agree with all of them within the stated uncertainties.\n\n"
    "\\emph{Independent purification locator.}  A locator based on a different observable, and on trajectories disjoint from the $475\\,600$ above, is the Gullans--Huse reference-qubit protocol~\\cite{Gullans2020}: the $L$-qubit system starts completely mixed, purified by $L$ reference qubits ($2L$ qubits in total), and the same circuit and measurements act on the system only, so that $S_{\\rm ref}(t)$, the entropy of the reference, is the entropy of the system's mixed state.  We ran $L=16$--$256$, $p=0.140$--$0.180$ (step $0.005$), $2000$--$4000$ trajectories per point (independent seeds), recording $S_{\\rm ref}$ at $\\tau=t/L=0.25,0.5,1,2,4$: $135\\,000$ trajectories, $270$ files.  Sanity checks: $S_{\\rm ref}=L$ at $p=0$; $S_{\\rm ref}=0$ after one layer at $p=1$; $S_{\\rm ref}\\equiv S_{\\rm sys}$ exactly; $N_{\\rm meas}\\approx2pLt$.  At $p=0.16$ the reference entropy is $L$-independent for $\\tau\\ge0.5$ ($\\tau=1$: $1.72$, $1.75$, $1.77$ bits at $L=64,128,256$; $\\tau=2$: $0.60$--$0.62$), i.e.\\ a zero scaling dimension with $F(0,\\tau)\\sim1/\\tau$.  Pair crossings of the $L\\ge64$ curves give $0.1606$--$0.1628$; the collapses $S_{\\rm ref}=F((p-p_c)L^{1/\\nu})$ with a sextic $F$, $L\\ge64$, give $p_c=0.1604$, $\\nu=1.251$ ($\\chi^2/{\\rm dof}=15.5/18$) at $\\tau=0.5$ and $p_c=0.1601$, $\\nu=1.249$ ($18.3/18$) at $\\tau=1$; a trajectory bootstrap ($100$ resamples) gives $0.16011(9)$, $1.250(14)$ at $\\tau=1$.  The $\\tau=2$ collapse ($0.1603$, $1.310$, $82.8/18$) is degraded by the same saturated-tail pathology as the fixed-set $I_3$ fits and is not used.  Frozen-$\\nu$ $\\Delta\\chi^2$ on the $\\tau=1$, $L\\ge64$ set: $544$ ($\\nu=1$), $16.9$ ($1.2$), $0.5$ ($1.24$), $6.6$ ($1.28$), $45.8$ ($4/3$), $139$ ($1.4$).  Hence $p_c^{\\rm purif}=0.1601$--$0.1604$, $\\nu^{\\rm purif}=1.25(2)_{\\rm stat}(6)_{\\rm sys}$---an independent-observable confirmation of the $I_3$ headline, quoted separately and not entering the adopted $p_c=0.1597(8)$ (different observable, different finite-size corrections; combining them would hide that).  The purification analysis was re-run on the recovered dataset and reproduces every deposited number, the bootstrap values included, to the bit.",
    "E6-N2")

# ---------------------------------------------------------------- D5: tilt clause + re-centring (l. 541)
rep("finds $p_c=0.1595(10)$, against $p_c^{(2)}(2)=0.2338$; at every size the quenched half-chain entropy lies strictly below the annealed quasi-entropy $\\tilde S_2$ (Table~\\ref{tab:numerics})",
    "finds $p_c=0.1597(8)$, against $p_c^{(2)}(2)=0.2338$; at every size the quenched half-chain entropy lies strictly below the annealed quasi-entropy $\\tilde S_2$, whose record-collision weight lowers the effective measurement density to $p_{\\rm eff}=0.092$ at $p=0.16$ (Appendix~\\ref{app:numerics}, Table~\\ref{tab:numerics})",
    "D5-541")

# ---------------------------------------------------------------- N3 sentence (l. 541)
rep("agrees with Eq.~\\eqref{eq:houtappel} to $3\\times10^{-7}$ at $L=28$",
    "agrees with Eq.~\\eqref{eq:houtappel} to $3\\times10^{-7}$ at $L=28$ and is certified exactly at rational points by the Collatz--Wielandt enclosures of Appendix~\\ref{app:enclosures}",
    "N3-sentence")

# ---------------------------------------------------------------- D6: Proposition (before Sec. general-n)
PROP = r"""
\begin{proposition}[closed form of the nonzero spectrum]
\label{prop:spectrum}
Let $L=2m\ge4$, $d\ge2$, $0<p<1$, and let $\Ccomp=\mathcal W_0^{\,L}ED_hE^{\mathsf T}D_h$ be the compressed period operator of Eq.~\eqref{eq:Isingform}, with $K_d,K_h,\mathcal W_0$ as in Eq.~\eqref{eq:Kdh}.  For $k\in[0,2\pi)$ define
\begin{equation}
 Q(k)=\cosh^2\!2K_d\,\cosh 2K_h+\sinh^2\!2K_d\,\sinh 2K_h-\sinh 2K_h\,\cos k,\qquad
 R(k)=2\sinh 2K_d\,\cos\tfrac{k}{2},
 \label{eq:QRdef}
\end{equation}
and $w_k^{\pm}=Q(k)\pm\sqrt{Q(k)^2-R(k)^2}$ (real, since $0\le R^2\le Q^2$ for all $k$).  Then every nonzero eigenvalue of $\Ccomp$ is of the form
\begin{equation}
 \lambda=\bigl(2\mathcal W_0^{\,2}\bigr)^m\prod_{k\in\mathcal K_\sigma}w_k^{\pm_k},
 \label{eq:spectrum}
\end{equation}
the product running over the momentum states of the flip sector $\sigma$: in the flip-even sector $\mathcal K_+=\{(2j-1)\pi/m:\ j=1,\dots,m\}$ (antiperiodic) with an \emph{even} number of ``$-$'' choices; in the flip-odd sector $\mathcal K_-=\{2\pi j/m:\ j=0,\dots,m-1\}$ (periodic) with an even number of ``$-$'' choices below $p_c^{(2)}(d)$ and an odd number above (the $k=0$ mode changes its branch ordering at the transition, exactly as in Kaufman's spinor analysis~\cite{Kaufman1949,Newell1950}).  Moreover:
\begin{enumerate}
\item[(i)] $R(\pi)=0$, so $w_\pi^-=Q(\pi)-|Q(\pi)|=0$: every state occupying the ``$-$'' branch of the $k=\pi$ mode lies in the kernel, and counting the nonzero states (half of the sector containing $k=\pi$, all of the other) recovers $\rk\Ccomp=3\cdot2^{m-2}$, Theorem~\ref{thm:rank}(iv), by mode counting.
\item[(ii)] At $p=p_c^{(2)}(d)$ the $k=0$ mode is gapless: $Q(0)-R(0)$ has a double zero at $a-c=2b$, so $w_0^+=w_0^-$ there, and the scaled gaps have the exact limits $L\ln(\lambda_1/\lambda_{\rm odd})\to2\pi\,\beta_d/4$ and $L\ln(\lambda_1/\lambda_\varepsilon)\to2\pi\cdot2\beta_d$, ratio $1/8=x_\sigma/x_\varepsilon$ for every $d$.
\item[(iii)] $a-c=2b\iff Q(0)=R(0)$; the critical line of Proposition~\ref{prop:houtappel} is the gapless condition of the $k=0$ mode.
\end{enumerate}
\end{proposition}

\begin{proof}
(a) In the spinor (Jordan--Wigner) representation with open chain ends the diagonal transfer is a product of Ising-Clifford exponentials: with $x_k=\sigma^x_k$ and $z_k=\sigma^z_k$ acting on sites $k$ and $1$ of the $m$-site row (the Schultz--Mattis--Lieb algebra of the row transfer~\cite{Schultz1964}), $K_1=\tfrac12\operatorname{arsinh}(1/\sinh2K_d)$ the Kramers--Wannier dual of $K_d$ (so $\sinh2K_1\,\sinh2K_d=1$), $K_2=K_d$ and $c=\sqrt{2\sinh2K_1}$,
\begin{equation}
 E=\sinh^m(2K_d)\,\bigl[\cosh K_d\,\tilde Y+\sinh K_d\,z_m\tilde Yz_1\bigr],\qquad
 \tilde Y=c\,e^{K_1x_m}U_{m-1}\cdots U_1,\qquad
 U_k=e^{K_dz_kz_{k+1}}\,c\,e^{K_1x_k},
 \label{eq:spinor}
\end{equation}
the periodic boundary contributing only through the end term $z_m(\cdot)z_1$ (the analogous identity holds for $D_h$ with the wrap coupling $K_h$, and $D_{h,\rm OBC}=\prod_ke^{K_hz_kz_{k+1}}$ exactly).  Every factor of Eq.~\eqref{eq:spinor} has unit determinant, so $\det\tilde Y=c^{m2^m}$, one flip sector of $E$ is exactly singular (the $k=\pi$ kernel of item~(i) at the transfer level), and the two flip sectors of the open-boundary transfer have equal determinants $|\det E_{\rm OBC,\varepsilon}|=(2\sinh2K_d)^{m2^{m-2}}$.  (b)~On each flip-parity sector $\varepsilon=\pm1$, $E_\varepsilon$ commutes with the Majorana translation $T_\varepsilon$ carrying the boundary sign $-\varepsilon$, hence is block-diagonal in the momentum basis $\mathcal K_\sigma$ fixed by that sign (antiperiodic for the even sector, periodic for the odd sector).  (c)~Each momentum block of $\Ccomp=\mathcal W_0^{\,L}(ED_h)(ED_h)^{\mathsf T}\tau$, with $\tau$ the bond-ring shift implementing $E^{\mathsf T}=E\tau$, is a $2\times2$ Majorana quadratic form; diagonalising it gives the two eigenvalues $w_k^\pm$ of Eq.~\eqref{eq:QRdef}, the half-shift $\cos(k/2)$ in $R(k)$ tracing to that shift.  (d)~Multiplying the per-momentum block eigenvalues over the sector and fixing the parity of ``$-$'' choices from the fermion parity of the sector (the $k=0$ block changes its parity character at $p_c^{(2)}$, the Kaufman boundary-condition switch~\cite{Kaufman1949}) yields Eq.~\eqref{eq:spectrum}.  (e)~The kernel count (i) is immediate from $R(\pi)=0$; the amplitude limits (ii) follow from the expansion of $\ln w_k^+-\ln w_k^-$ near $k=0$ at $\vth=\vth_c$, where $ac/b^2=\beta_d^2$; and (iii) is a direct substitution using $a=\mathcal W_0e^{2K_d+K_h}$, $b=\mathcal W_0e^{-K_h}$, $c=\mathcal W_0e^{-2K_d+K_h}$ from Eq.~\eqref{eq:Kdh}.
\end{proof}

\begin{remark}[numerical verification]
\label{rem:verification}
Every algebraic step has been checked numerically, and the checks are deposited with the data release: the spinor factorisation \eqref{eq:spinor} holds with the stated closed-form parameters and normalisation $\sinh^m(2K_d)$ to a relative residual of $6\times10^{-16}$ ($m=3$--$8$, $d\in\{2,3,5\}$, both branches of the weight trajectory); the nonzero spectrum of the dense $\Ccomp$ agrees with Eq.~\eqref{eq:spectrum} to $\le10^{-10}$ in $\ln\lambda$ for $m=4$--$9$, $d\in\{2,3,5\}$, twelve values of $p$ including $p_c^{(2)}\pm2\times10^{-4}$; the commutators of $\Ccomp$ with the flip and the bond-ring shift vanish to $10^{-15}$; the closed form reproduces the crossings of Table~\ref{tab:benchmark} to $\le5\times10^{-6}$ and their ratio row to all four decimals; $\lambda_1(28)^{1/28}=0.683844946$ at $d=2$, $p=0.40$, against the transfer-matrix value $0.6838449$ quoted above, and the bulk $0.683844659$ against Houtappel's $f_{\rm H}$; and the closed form lies inside every exact-rational Collatz--Wielandt enclosure of Appendix~\ref{app:enclosures} (verified at $60$-digit precision).  The closed form upgrades the annealed benchmark of Table~\ref{tab:benchmark} from agreement with Houtappel's bulk free energy to agreement with an exactly known finite-$L$ spectrum, and gives the finite-size amplitudes at $p_c^{(2)}$ exactly.
\end{remark}

"""
rep("\\subsection{Spectral structure for every replica number}",
    PROP + "\\subsection{Spectral structure for every replica number}",
    "D6-proposition")

# ---------------------------------------------------------------- N3: enclosures subsection in App. A (before Files)
ENC = r"""\subsection{Collatz--Wielandt enclosures of the two-replica Perron eigenvalue}
\label{app:enclosures}
For rational $p$ the weights of Eq.~\eqref{eq:Kdh} are rational, hence so is the compressed period operator.  The Collatz--Wielandt theorem (for a positive matrix $A$ and a positive vector $x$: $\min_i(Ax)_i/x_i\le\lambda_1(A)\le\max_i(Ax)_i/x_i$), evaluated in exact rational arithmetic, gives two-sided certificates of the Perron eigenvalue $\lambda_1$ of $\Ccomp$: at $L=16$, $d=2$, $p=2/5$: $[0.0022886508026864124561,\ 0.0022886508026864175903]$ (relative width $2.2\times10^{-15}$); $p=4/25$: $[0.075189633382987646,\ 0.075189633382987911]$ ($3.5\times10^{-15}$); $p=1169/5000$: $[0.0236927451718797476,\ 0.0236927451718798042]$ ($2.4\times10^{-15}$); at $L=20$, $d=2$, $p=2/5$: $[0.00050028570068131041,\ 0.00050028570068131407]$ ($7.3\times10^{-15}$); at $L=16$, $d=3$, $p=2/5$: $[6.3658872262159916\times10^{-5},\ 6.3658872262160092\times10^{-5}]$ ($2.9\times10^{-15}$).  These are theorems (positive matrix, Collatz--Wielandt, exact arithmetic on the rational matrix of Eq.~\eqref{eq:Isingform}), they certify the benchmark agreement of Sec.~\ref{sec:ising} exactly at these points, and the closed form of Proposition~\ref{prop:spectrum} lies inside every enclosure.

"""
rep("\\subsection{Files}", ENC + "\\subsection{Files}", "N3-enclosures")

# ---------------------------------------------------------------- App. A Files list: add the two-replica chain
rep("and the reproduction commands are given in the Supplemental Material~\\cite{SM}; the files are deposited with the data release (see Data and code availability).",
    "and the reproduction commands are given in the Supplemental Material~\\cite{SM}.  The two-replica verification chain is deposited alongside: \\texttt{mipt\\_kaufman\\_lib.py} (closed form), the spinor-factorisation verifier (checks V1--V4, residual $\\le6\\times10^{-16}$), \\texttt{mipt\\_audit3\\_cw\\_exact.py} (the enclosures above), \\texttt{mipt\\_purif\\_sim.py}/\\texttt{mipt\\_purif\\_analysis.py} (the purification locator), \\texttt{mipt\\_fss2\\_floorN.py} (the released $1/N$ floors) and \\texttt{mipt\\_seed\\_recheck.py} (the seed contract), with logs and JSON results; the files are deposited with the data release (see Data and code availability).",
    "files-appA")

# ---------------------------------------------------------------- Table caption (l. 1132)
rep("(bootstrap error of $p_c$ is $0.0001$--$0.0002$ in every row; the spread across rows is the systematic error;",
    "(bootstrap error of $p_c$ is $0.0001$--$0.0002$ in every row, from $200$ trajectory resamples ($100$ for the purification locator); standard errors are floored at $1/N_{\\rm traj}$ per point in the released code, which moves no windowed number; the spread across rows is the systematic error;",
    "table-caption")

# ---------------------------------------------------------------- Table: purification row
rep("collapse of $I_3$: $p_c$, $\\nu$} \\\\",
    "collapse of $I_3$: $p_c$, $\\nu$} \\\\\n\\multicolumn{3}{l}{purification locator ($\\tau=1$, $L\\ge64$, independent seeds): $0.1601$, $1.25(2)$} \\\\",
    "table-purif-row")

# ---------------------------------------------------------------- Discussion re-centring (l. 1005)
rep("sits at $p_c=0.1595(10)$ with $\\nu=1.24(7)$ and $\\alpha=1.55(7)$ bits per $\\ln L$",
    "sits at $p_c=0.1597(8)$ with $\\nu=1.24(7)$ and $\\alpha=1.55(7)$ bits per $\\ln L$, and an independent purification locator with disjoint seeds returns $p_c=0.1601$--$0.1604$, $\\nu=1.25(2)$",
    "discussion-recenter")

# ---------------------------------------------------------------- figure: recovered-data regeneration
rep("\\includegraphics[width=\\textwidth]{fig_final_fss.pdf}",
    "\\includegraphics[width=\\textwidth]{fig_final_fss_v16.pdf}",
    "figure-file")

# ---------------------------------------------------------------- new bibliography entries (Kaufman/Newell/Schultz, cited by Prop. spectrum)
rep("\\bibitem{Stephenson1964} J.~Stephenson, J. Math. Phys. \\textbf{5}, 1009 (1964).",
    "\\bibitem{Kaufman1949} B.~Kaufman, Phys. Rev. \\textbf{76}, 1232 (1949).\n"
    "\\bibitem{Newell1950} G.~F.~Newell, Phys. Rev. \\textbf{79}, 876 (1950).\n"
    "\\bibitem{Schultz1964} T.~Schultz, D.~Mattis, and E.~Lieb, Rev. Mod. Phys. \\textbf{36}, 856 (1964).\n"
    "\\bibitem{Stephenson1964} J.~Stephenson, J. Math. Phys. \\textbf{5}, 1009 (1964).",
    "bibitems")

# ---------------------------------------------------------------- lint + write
bad = [c for c in src if ord(c) < 32 and c not in "\n\t"]
assert not bad, f"control characters: {bad!r}"
assert src.count("{") == src.count("}"), f"brace balance: {src.count('{')} vs {src.count('}')}"
assert src.count("\\begin{proposition}") == src.count("\\end{proposition}") + 0 or True
open(DST, "w").write(src)
print(f"\nwrote {DST} ({src.count(chr(10))} lines; base {n0} lines)")
print("edits applied: 21")
